### ISSUE TITLE
这样写不就空指针了吗

### ISSUE THREAD

**Issue by Blizzard-liu** [xiong-it/EasyPay#10]
![image](https://user-images.githubusercontent.com/20244432/28261507-27793b04-6b12-11e7-9e3a-3d830a55ccae.png)

**Comment by xiong-it** [comment]
当某个参数申明可为空(@Nullable)，并且不做null拦截抛异常的话，是可以传递null为实参的，不会空指针异常。

**Comment by Blizzard-liu** [comment]
但是你参数都没传  appid从哪取出来的呢

**Comment by Blizzard-liu** [comment]
![image](https://user-images.githubusercontent.com/20244432/28262881-54f35e48-6b17-11e7-9a7c-b3b70d6d45f2.png)


我说的空指针应该在这

**Comment by xiong-it** [comment]
这个问题请问是实践过得到的空指针吗？理论上是不会的。

**Comment by Blizzard-liu** [comment]
没有实践  但你看上面两个截图  mPayParams 传的是null   再调用get()方法不就空指针了吗

**Comment by xiong-it** [comment]
试想，你要调起支付，首先需要干嘛？
```
PayParams params = new PayParams.Builder(this)
                .wechatAppID("your_wechat_appid")// 仅当支付方式选择微信支付时需要此参数
                .payWay(PayWay.WechatPay)
                .goodsPrice(66600)// 单位为：分
                .goodsName("皮皮虾")
                .goodsIntroduction("此商品属性过于强大，难以调教，一般人切勿轻易购买，吼吼！")
                .httpType(HttpType.Get)
                .httpClientType(NetworkClientType.Retrofit)
                .requestBaseUrl("http://blog.csdn.net/")// 此处替换为为你的app服务器host主机地址
                .build();

        EasyPay.newInstance(params)...
```
是不是已经将params传进去了sInstance？之后调起了支付，微信打开了WXPayEnteryActivity，此时params传null，是不是没有影响呢？因为sInstance是刚才构建的sInstance，其中已经保存了params对象实例，为何会空指针？如果实践后仍有问题，麻烦及时反馈，十分感谢！

**Comment by Blizzard-liu** [comment]
你说的对  请问支付宝授权那块不重要吗,你没写进去
