### ISSUE TITLE
怎么不以jar的形式发布到jcenter，这样调用的方式会不会更简单一点，哈哈

### ISSUE THREAD

**Issue by china-coder** [xiong-it/EasyPay#11]

**Comment by Javen205** [comment]
这里有一个微信、支付宝的封装已发布到jar可以直接使用
https://github.com/Javen205/JPay

**Comment by china-coder** [comment]
谢谢

**Comment by Javen205** [comment]
@china-coder 不客气  @xiong-it 可以参这篇文章发布开源项目到  Jitpack
http://blog.csdn.net/zyw_java/article/details/75795723

**Comment by xiong-it** [comment]
@china-coder 你好，本项目是一个开发脚手架，需要开发人员改动以适应需求。

**Comment by china-coder** [comment]
好的，使用的过程中，体会到了这一点
