### ISSUE TITLE
下载工程依赖的过程中各种dumplicate entry

### ISSUE THREAD

**Issue by ganshenml** [xiong-it/EasyPay#4]
还是依赖直接得好。不断删除现有工程的依赖和jar包真的还是有点伤啊。

**Comment by xiong-it** [comment]
实际上，本工程已经依赖了最新的支付宝和微信sdk，并且使用了最新的okhttp3，retrofit2，还有volley。如果版本不适合，可以建立一个base module，导入app和library所需的共同依赖，让library依赖base，让app依赖base和library。希望有所帮助。good luck！

**Comment by Javen205** [comment]
@ganshenml   简洁而不简单的JPay  只依赖官方的jar   https://github.com/Javen205/JPay

**Comment by ganshenml** [comment]
@Javen205 @xiong-it 谢谢
