### ISSUE TITLE
在没有网络的情况下会空指针导致程序崩溃

### ISSUE THREAD

**Issue by YuPf1989** [xiong-it/EasyPay#6]
原因是：
在EasyPay类中,先是在requestPayInfo()中调用了一次sendPayResult();即调用了一次 releaseMemory();此时mPayParams为null，后来又在toPay()中又调用了一次。
mOnPayResultListener.onPayFailure(mPayParams.getPayWay(), code);mPayParams.getPayWay()为空指针。
建议将releaseMemory()方法放在doPay()中

**Comment by xiong-it** [comment]
thx，fixed.
